version: '3.8'

services:
  # Node.js application container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veg_fruit_store_app
    ports:
      - "3000:3000"  # Expose app on port 3000
    environment:
      - NODE_ENV=production
      - DB_HOST=db  # PostgreSQL service name in Docker Compose
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=veg_fruit_store
    volumes:
      - .:/usr/src/app  # Synchronize local code with container
    depends_on:
      - db  # Make sure the app waits for the db to be ready
    networks:
      - veg_fruit_network
    command: ["npm", "run", "start"]  # Start the app

  # PostgreSQL database container
  db:
    image: postgres:13  # Use PostgreSQL 13
    container_name: veg_fruit_store_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: veg_fruit_store
    volumes:
      - veg_fruit_store_db_data:/var/lib/postgresql/data  # Persist data across container restarts
    networks:
      - veg_fruit_network

networks:
  veg_fruit_network:
    driver: bridge

volumes:
  veg_fruit_store_db_data:
    driver: local
